version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DOCKER_SERVER_PORT=${DOCKER_SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${DOCKER_SERVER_PORT}

  
