version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${DOCKER_SERVER_PORT}
    container_name: SmartFit-backend
  forntend:
    build: 
      args:
        - SERVER_PORT=${SERVER_PORT}
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${DOCKER_APP_PORT}
    container_name: SmartFit-frontend
    stdin_open: true
    tty: true


  

  
##finished frontend too , to run evreything just type : docker-compose up -d --build and if you want
##to change something do that through the .env file 

##note to self , remove proxy from package.json 